# Generated by Django 2.2.1 on 2019-05-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('content', models.FileField(unique=True, upload_to='uploaded_articles')),
                ('thumbnail', models.ImageField(upload_to='uploaded_articles')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='articles_written', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='articles_tagged', to='articles.Tag')),
            ],
        ),
    ]
