# Generated by Django 2.2.1 on 2019-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190511_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, db_column='data_created'),
        ),
    ]
